apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: login-service
      port: {{ .Values.login.ports.client }}
      targetPort: {{ .Values.login.ports.client }}
      nodePort: {{ .Values.service.login }}
  selector:
    app: login
