apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}
          imagePullPolicy: {{ .Values.imagepolicy }}
          ports:
            - containerPort: {{ .Values.zookeeper.ports.client }}
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
